### ISSUE TITLE
Great job on your pastebin userstyle, but it needs some work

### ISSUE THREAD

**Issue by deusexcalamus** [Psykek66/UserCSS#3]
As the subject says, some things are incorrectly formatted/hard to see, I'll attach a screenshot or two...
![pastebintheme](https://user-images.githubusercontent.com/8674645/93385689-36365000-f82c-11ea-9ce4-5f5762fd80f0.png)
As you can see, some of the elements are near impossible to read, such as titles of saved pastes (which are a dark blue color until you hover over them, then they get a white box), your username/account info in the top left, etc. The grey text on a white background for the infobox below your saved pastes is also really hard to read, think you can manage something about that?

**Comment by Psykek66** [comment]
Thanks, and I'm aware of this. I had the theme fully setup before, but they updated the website and it made most of the code useless. I updated it to fix the most basic stuff since someone requested it, but I stopped after that. I'm not sure when I'll get around to actually fixing it, but I will one day.

**Comment by deusexcalamus** [comment]
At least its usable-ish as is, and not totally broken like the ones on userstyles.org.
I guess you can close this or w/e.
